site_name: 蒙太奇字幕百科 | MontageSubs Wiki
site_description: 一本众创、共建、同享的字幕百科。
site_author: MontageSubs Community
site_url: https://montagesubs.github.io/wiki/

edit_uri: https://github.com/MontageSubs/wiki/wiki/

theme:
  name: material
  custom_dir: overrides
  language: zh
  logo: site/assets/montagesubs_logo-512.jpg
  favicon: site/assets/favicon.ico
  
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tooltips

  hide:
    - footer.powered

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 跟随系统模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换至日间模式

plugins:
  - search

markdown_extensions:
  - md_in_html
  - admonition
  - footnotes
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

extra_css:
  - site/stylesheets/extra.css

extra:
  translations:
    edit.link.title: "在 Wiki 中编辑此页"
    view.link.title: "查看本页编辑历史"

  social:
    - icon: fontawesome/brands/github
      link: https://montagesubs.github.io
    - icon: fontawesome/solid/paper-plane
      link: https://t.me/s/MTSubs
    - icon: fontawesome/brands/weibo
      link: https://weibo.com/u/8358891788
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/montagesubs.bsky.social

copyright: |
  Copyright &copy; 2026 <a href="https://montagesubs.github.io">MontageSubs</a>
